#FemtoCraft 1.28 configuration file
#For instructions, see http://femto.fcraft.net/#configuration

server-name=Docker Wine ClassiCube Server
motd=Welcome to the ClassiCube Server!
port=25572
ip=0.0.0.0
max-players=20
public=False
verify-names=False
use-whitelist=False
admin-slot=True
reveal-ops=False
heartbeat-url=http://www.classicube.net/server/heartbeat

max-connections=3
limit-click-rate=True
limit-click-distance=True
limit-chat-rate=True
allow-speed-hack=True

op-max-connections=3
op-limit-click-rate=True
op-limit-click-distance=True
op-limit-chat-rate=True
op-allow-speed-hack=True

physics=True
physics-tick=50
physics-flood-protection=False
physics-grass=True
physics-lava=True
physics-plants=True
physics-sand=True
physics-snow=True
physics-trees=True
physics-water=True

allow-water-blocks=False
allow-lava-blocks=False
allow-grass-blocks=True
allow-solid-blocks=True
op-allow-water-blocks=True
op-allow-lava-blocks=True
op-allow-grass-blocks=True
op-allow-solid-blocks=True

protocol-extension=True
